name: Build Frontend

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  checkout-lint-build:
  
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
     
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Lint (TS)
        working-directory: ./frontend
        run: |
              yarn run
              yarn lint
      
      - name: Build
        run: |
              yarn install --frozen-lockfile
              yarn build
    
             
        
