name: Mypy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  mypy-type-checking:
    # https://dev.to/po5i/github-action-to-run-mypy-on-changed-files-only-3iip
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r backend/requirements.txt # you can pin your preferred version
      - name: Run type checks
        run: mypy backend
