name: Mypy

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  mypy-type-checking:
    # https://dev.to/po5i/github-action-to-run-mypy-on-changed-files-only-3iip
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - run: pip install mypy  # you can pin your preferred version
    - name: Get Python changed files
      id: changed-py-files
      uses: tj-actions/changed-files@v23
      with:
        files: |
          *.py
          **/*.py
    - name: Run if any of the listed files above is changed
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: mypy ${{ steps.changed-py-files.outputs.all_changed_files }} --ignore-missing-imports
